#!/bin/bash
set -e

# Script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

FUNNEL_NAME="$(basename "$DIR")"

echo "=================================================="
echo "🚀 Production-Safe Persistent Launcher for $FUNNEL_NAME"
echo "=================================================="

# 1. Install dependencies
echo "📦 Installing backend dependencies..."
(cd backend && npm install)

echo "📦 Installing frontend dependencies..."
(cd frontend && npm install)

BACKEND_PORT=9045
FRONTEND_PORT=9040

echo "🔍 Target Ports -> Backend: $BACKEND_PORT | Frontend: $FRONTEND_PORT"

# Safe process cleanup: ONLY stop PIDs generated by this funnel's previous start
if [ -f "$DIR/backend.pid" ]; then
    OLD_BE_PID=$(cat "$DIR/backend.pid")
    if ps -p "$OLD_BE_PID" > /dev/null 2>&1; then
        echo "🛑 Stopping previous backend PID $OLD_BE_PID..."
        kill "$OLD_BE_PID" 2>/dev/null || true
    fi
    rm -f "$DIR/backend.pid"
fi

if [ -f "$DIR/frontend.pid" ]; then
    OLD_FE_PID=$(cat "$DIR/frontend.pid")
    if ps -p "$OLD_FE_PID" > /dev/null 2>&1; then
        echo "🛑 Stopping previous frontend PID $OLD_FE_PID..."
        kill "$OLD_FE_PID" 2>/dev/null || true
    fi
    rm -f "$DIR/frontend.pid"
fi

sleep 1

# 4. Start Backend (Detached using nohup + disown)
echo "⚡ Launching Backend API on http://localhost:$BACKEND_PORT ..."
nohup bash -c "cd '$DIR/backend' && PORT=$BACKEND_PORT npx tsx server.ts" > "$DIR/backend.log" 2>&1 &
BACKEND_PID=$!
disown $BACKEND_PID
echo $BACKEND_PID > "$DIR/backend.pid"

# 5. Start Frontend (Detached using nohup + disown)
echo "⚡ Launching Frontend App on http://localhost:$FRONTEND_PORT ..."
nohup bash -c "cd '$DIR/frontend' && npx vite --host 0.0.0.0 --port $FRONTEND_PORT" > "$DIR/frontend.log" 2>&1 &
FRONTEND_PID=$!
disown $FRONTEND_PID
echo $FRONTEND_PID > "$DIR/frontend.pid"

# 6. Verify service startup
echo "⏳ Waiting for services to respond..."
sleep 5

BACKEND_HTTP=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${BACKEND_PORT}/ || echo "FAILED")
FRONTEND_HTTP=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${FRONTEND_PORT}/ || echo "FAILED")

echo "=================================================="
echo "📊 VERIFICATION REPORT ($FUNNEL_NAME)"
echo "=================================================="
echo "Backend  (Port $BACKEND_PORT) : HTTP $BACKEND_HTTP [PID: $BACKEND_PID]"
echo "Frontend (Port $FRONTEND_PORT) : HTTP $FRONTEND_HTTP [PID: $FRONTEND_PID]"
echo "Backend Log  : $DIR/backend.log"
echo "Frontend Log : $DIR/frontend.log"
echo "=================================================="

if [ "$BACKEND_HTTP" = "200" ] && [ "$FRONTEND_HTTP" = "200" ]; then
    echo "✅ Success! Both backend and frontend are running persistently."
    echo "📌 You can safely close your terminal; services will remain active!"
else
    echo "⚠️ Warning: Check logs if service status is not HTTP 200."
fi
